<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>UVL Metadata</AssemblyTitle>
    <Product>UVL Metadata</Product>
    <RootNamespace>UVLMetadata</RootNamespace>
    <AssemblyName>UVLMetadata</AssemblyName>
    <Company>HerrKnarz</Company>
    <Copyright>Copyright © 2026 under MIT license</Copyright>
    <Platform>AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <TargetFramework>net462</TargetFramework>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <LangVersion>14</LangVersion>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>0.6.2</Version>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Web" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\KNARZhelper\KNARZhelper\Controls\SettingsOption.cs" Link="Shared\Controls\SettingsOption.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\Controls\SettingsSection.cs" Link="Shared\Controls\SettingsSection.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\Enum\DbInteractionResult.cs" Link="Shared\Enum\DbInteractionResult.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\FilesCommon\FileHelper.cs" Link="Shared\FilesCommon\FileHelper.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\GamesCommon\GameEx.cs" Link="Shared\GamesCommon\GameEx.cs" />
	  <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\BaseMetadataObject.cs" Link="Shared\MetadataCommon\BaseMetadataObject.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\BaseListType.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\BaseListType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\BaseObjectType.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\BaseObjectType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\IClearAbleType.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\IClearAbleType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\IEditableObjectType.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\IEditableObjectType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\IGameInfoType.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\IGameInfoType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\IMetadataFieldType.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\IMetadataFieldType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\IObjectType.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\IObjectType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\IValueType.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\IValueType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\TypeAgeRating.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\TypeAgeRating.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\TypeFeature.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\TypeFeature.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\TypeGenre.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\TypeGenre.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\TypeSeries.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\TypeSeries.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\DatabaseObjectTypes\TypeTag.cs" Link="Shared\MetadataCommon\DatabaseObjectTypes\TypeTag.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\Enum\FieldType.cs" Link="Shared\MetadataCommon\Enum\FieldType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\Enum\ItemValueType.cs" Link="Shared\MetadataCommon\Enum\ItemValueType.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\ViewModels\SelectMetadataViewModel.cs" Link="Shared\MetadataCommon\ViewModels\SelectMetadataViewModel.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\Views\SelectMetadataView.xaml.cs" Link="Shared\MetadataCommon\Views\SelectMetadataView.xaml.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\WebCommon\Models\UrlLoadResult.cs" Link="Shared\WebCommon\Models\UrlLoadResult.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\WebCommon\LinkWorker.cs" Link="Shared\WebCommon\LinkWorker.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\WebCommon\WebHelper.cs" Link="Shared\WebCommon\WebHelper.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\AsyncHelper.cs" Link="Shared\AsyncHelper.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\Log.cs" Link="Shared\Log.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\MiscHelper.cs" Link="Shared\MiscHelper.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\PlatformHelper.cs" Link="Shared\PlatformHelper.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\StringHelper.cs" Link="Shared\StringHelper.cs" />
    <Compile Include="..\..\KNARZhelper\KNARZhelper\WindowHelper.cs" Link="Shared\WindowHelper.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="extension.yaml" CopyToOutputDirectory="Always" />
    <None Include="icon.png" CopyToOutputDirectory="Always" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Localization\*.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Page Include="..\..\KNARZhelper\KNARZhelper\Controls\CommonStyles.xaml">
      <Link>Shared\Controls\CommonStyles.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\KNARZhelper\KNARZhelper\Controls\SettingsStyles.xaml">
      <Link>Shared\Controls\SettingsStyles.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
	<Page Include="..\..\KNARZhelper\KNARZhelper\MetadataCommon\Views\SelectMetadataView.xaml">
      <Link>Shared\MetadataCommon\Views\SelectMetadataView.xaml</Link>
	  <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="0.9.9" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="PlayniteSDK" Version="6.16.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\uvl-logo-white.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
