namespace KNARZhelper.Enum
{
    public enum FieldType
    {
        AgeRating = 5,
        Background = 13,
        Category = 0,
        CompletionStatus = 10,
        CommunityScore = 16,
        Cover = 15,
        CriticScore = 17,
        DateAdded = 20,
        Description = 21,
        Developer = 6,
        Favorite = 24,
        Feature = 1,
        Genre = 2,
        Hdr = 29,
        Hidden = 25,
        Icon = 14,
        InstallSize = 31,
        IsInstalled = 26,
        LastPlayed = 23,
        Library = 11,
        Name = 32,
        Notes = 22,
        Platform = 7,
        PlayCount = 27,
        Publisher = 8,
        OverrideInstallState = 30,
        Region = 12,
        ReleaseDate = 19,
        Series = 3,
        SortingName = 33,
        Source = 9,
        Tag = 4,
        TimePlayed = 28,
        UserScore = 18,
    }
}